### PR TITLE
Clarifying ambiguity of the term "NServiceBus" in our repositories' License file

### PR DESCRIPTION
**Pull request by udidahan**
In order to address https://github.com/Particular/CustomerSuccess/issues/1930

The language proposed here would cover all code in all the repositories in our GitHub organization, including those which do not use the name NServiceBus in them, like ServiceInsight or ServicePulse.

### CODE REVIEW

**Comment by karenfruchtman** [comment]
@udidahan Can you explain why it's better to use Particular Software here?

**Comment by udidahan** [comment]
@karenfruchtman updated the description to explain.

**Review by karenfruchtman — APPROVED** [review]

**Review by andreasohlund — APPROVED** [review]

**Review by dvdstelt — APPROVED** [review]

**Comment by udidahan** [comment]
Taking this forward as a [small decision](https://github.com/Particular/StaffSuccess/blob/master/guidelines/decision-making.md#for-small-decisions), given the approvals, I think I can go ahead and post an FYI, although I'm not sure that needs to go to the `announcements` channel. Any suggestions for a more appropriate place? `CustomerSuccess` and `Risk` possibly?

**Comment by karenfruchtman** [comment]
@udidahan I agree, CS and Risk channels are sufficient.  Will you comment on the issue and close it?

**Comment by udidahan** [comment]
Does any work need to be done to sync these changes out to all of our repositories, or do we have automation that covers it?

**Comment by DavidBoike** [comment]
Automation will raise a ton of PRs. The automation isn’t great at the moment because it will hit rate limits on GitHub, so over the next couple days all the PRs will get created (unfortunately along with a bunch of extra branches from the failures) but we have scripts to help merge all the PRs and clean up the mess.

**Pull request merged**
