### PR TITLE
Add standard CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by bording**

### CODE REVIEW

**Comment by andreasohlund** [comment]
Lets link to this from https://github.com/Particular/PlatformDevelopment/tree/master/repo-standards ?

**Comment by bording** [comment]
@andreasohlund I don't understand your comment.

**Comment by andreasohlund** [comment]
I meant to document the fact that platdev owns the content of this file?

**Comment by bording** [comment]
> I meant to document the fact that platdev owns the content of this file?

How does that impact this PR? That's what I'm not understanding.

**Comment by andreasohlund** [comment]
I meant as a separate PR against platdev

**Pull request merged**
