### PR TITLE
Adding apache, MIT and RPL

### PR DESCRIPTION
**Pull request by danielmarbach**

### CODE REVIEW

**Comment by danielmarbach** [comment]
currently the docs dual license is missing

**Comment by adamralph** [comment]
LGTM. Note: will have to be merged before https://github.com/Particular/PBot/pull/101

**Comment by danielmarbach** [comment]
@adamralph should we add the docs license? If yes how should the file look like?

**Comment by adamralph** [comment]
@danielmarbach I guess so. We can use this file https://github.com/Particular/docs.particular.net/blob/master/license.md and perhaps call it `MIT_APACHE.md`?

**Comment by danielmarbach** [comment]
@adamralph good to go? Hit the button?

**Comment by adamralph** [comment]
Thanks @danielmarbach !

**Pull request merged**
