### PR TITLE
Rename .dependabot.yml to dependabot.yml

### PR DESCRIPTION
**Pull request by adamralph**
While `.dependabot.yml` works, it should really be `dependabot.yml`.

See https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-and-disabling-version-updates

---

Update: it may be the `.dependabot.yml` doesn't work, and dependabot-preview is just filling in some of the gaps for us now. See [this Slack comment](https://particularsoftware.slack.com/archives/CEPBPQAUC/p1602712331047300) by @kbaley.

related dev standards PR - https://github.com/Particular/PlatformArchitecture/pull/695

### CODE REVIEW

**Comment by adamralph** [comment]
I want to find out if we can make an enhancement to our repo sync so that it won't necessarily push out all changes immediately to all repos, since it would be a bit ridiculous to spawn off a whole load of PR's just because of this rename.

Marking as a draft until that is investigated.

**Comment by adamralph** [comment]
Adding to the @Particular/platform-architecture-squad board, since it seems it may be important to get this in.

**Comment by andreasohlund** [comment]
> want to find out if we can make an enhancement to our repo sync so that it won't necessarily push out all changes immediately

A bit brute force but we can easily have a "max number of prs to raise" setting that the automation can honor that would do the trick

**Comment by danielmarbach** [comment]
If we had a proper CI system we wouldn't even have this discussion. The sooner we push the system to its knees the sooner we are getting a good replacement because it raises awareness. Let's unleash the horses!

**Comment by adamralph** [comment]
> want to find out if we can make an enhancement to our repo sync so that it won't necessarily push out all changes immediately

In the context of this PR, this has now become unimportant, since we've realised that this is actually important to roll out. That's why I removed the draft status.

Can I interest anyone in approving? 🙂

**Review by danielmarbach — APPROVED** [review]

**Pull request merged**
