### PR TITLE
Removed license files

### PR DESCRIPTION
**Pull request by ramonsmits**

### CODE REVIEW

**Comment by bording** [comment]
Where are we going to put these files instead? I don't think we want to completely get rid of them.

**Comment by andreasohlund** [comment]
Should we dump them into a gdrive folder just to have them around?

**Comment by andreasohlund** [comment]
@ramonsmits please dump the files in a google drive

**Comment by ramonsmits** [comment]
How about we put them in their own branch?

**Comment by andreasohlund** [comment]
Sounds legit

**Pull request merged**
