### PR TITLE
update ParticularAnalyzersVersion from 1.6.1 to 1.8.0

### PR DESCRIPTION
**Pull request by adamralph**
- https://github.com/Particular/Particular.Analyzers/issues?q=is%3Aclosed+milestone%3A1.7.0
- https://github.com/Particular/Particular.Analyzers/issues?q=is%3Aclosed+milestone%3A1.8.0

### CODE REVIEW

**Comment by DavidBoike** [comment]
@adamralph Before we merge this, could you give a review to https://github.com/Particular/NServiceBus/pull/6095 where I applied the new analyzers to Core?

**Comment by ramonsmits** [comment]
@DavidBoike @adamralph I see that this would introduce https://github.com/Particular/Particular.Analyzers/pull/117, I'm against that. You can't do drop in assembly replacements due to that change. I think the issue it solves with VS does not outweigh the potential deployment limitations. 

Did I get this correct or is this not impacted?

**Comment by DavidBoike** [comment]
@ramonsmits I'm confused. This assembly is only consumed by Visual Studio. It is not part of the build output. And https://github.com/Particular/Particular.Analyzers/pull/117 makes it do exactly what the NServiceBus analyzers are doing. The problem is that Visual Studio doesn't like drop-in assembly replacement. If you change to a new branch with a different version of Analyzers, but the AssemblyVersion of all of them is 1.0.0, then Visual Studio can't unload the previous branch's version and replace it with the new one, so you end up getting all sorts of errors and in the end you have to restart Visual Studio.

**Comment by ramonsmits** [comment]
@DavidBoike Ok, thanks for explaining. I thought it was applying new assembly versioning for Core and downstreams which based on your comment is not the case.

**Review by andreasohlund — APPROVED** [review]

**Pull request merged**
